apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: ravipativenu/myapp:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mysecret-volume
          mountPath: /etc/secrets/sapcp/hana/cpapp-db-instance
          readOnly: true
      volumes:
      - name: mysecret-volume
        secret:
          secretName: cpapp-db-binding
